#ifndef VOICE_COMMAND_SERVICE_H
#define VOICE_COMMAND_SERVICE_H

typedef enum
{
    VOICE_COMMAND_UNKNOWN = 0,
    VOICE_COMMAND_WAKEUP_ACK,
    VOICE_COMMAND_SLEEP_ACK,
    VOICE_COMMAND_FOOTBATH_START,
    VOICE_COMMAND_FOOTBATH_STOP,
    VOICE_COMMAND_MASSAGE_START,
    VOICE_COMMAND_MASSAGE_STOP,
    VOICE_COMMAND_TEMP_UP,
    VOICE_COMMAND_TEMP_DOWN,
    VOICE_COMMAND_GO_HOME,
    VOICE_COMMAND_DRY_START,
    VOICE_COMMAND_CLEAN_START,
    VOICE_COMMAND_CLEAN_STOP,
    VOICE_COMMAND_STOP_ALL,
    VOICE_COMMAND_WAKEUP,
    VOICE_COMMAND_NOISE
} voice_command_t;

int voice_command_service_init(void);
void voice_command_service_deinit(void);

#endif
