#ifndef ROBOT_CHASSIS_TYPES_H
#define ROBOT_CHASSIS_TYPES_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ROBOT_CHASSIS_DEFAULT_IP "192.168.31.7"
#define ROBOT_CHASSIS_DEFAULT_PORT 9970U
#define ROBOT_CHASSIS_FRAME_SUFFIX_SIZE 4U
#define ROBOT_CHASSIS_MAX_FRAME_SIZE (16U * 1024U * 1024U)
#define ROBOT_CHASSIS_QUEUE_CAPACITY 32U
#define ROBOT_CHASSIS_HEARTBEAT_INTERVAL_MS 15000U
#define ROBOT_CHASSIS_RECONNECT_INTERVAL_MS 3000U
#define ROBOT_CHASSIS_HEARTBEAT_MISS_LIMIT 3U
#define ROBOT_CHASSIS_MAP_POLL_INTERVAL_MS 500U
#define ROBOT_CHASSIS_UPGRADE_HEX_CHUNK_MAX (512U * 1024U)

typedef enum {
    ROBOT_CHASSIS_OK = 0,
    ROBOT_CHASSIS_ERR_INVALID_ARG = -1,
    ROBOT_CHASSIS_ERR_NO_MEMORY = -2,
    ROBOT_CHASSIS_ERR_QUEUE_FULL = -3,
    ROBOT_CHASSIS_ERR_NOT_CONNECTED = -4,
    ROBOT_CHASSIS_ERR_IO = -5,
    ROBOT_CHASSIS_ERR_WOULD_BLOCK = -6,
    ROBOT_CHASSIS_ERR_PEER_CLOSED = -7,
    ROBOT_CHASSIS_ERR_FRAME_INVALID = -8,
    ROBOT_CHASSIS_ERR_FRAME_TOO_LARGE = -9,
    ROBOT_CHASSIS_ERR_JSON = -10,
    ROBOT_CHASSIS_ERR_FORMAT = -11,
    ROBOT_CHASSIS_ERR_BUSY = -12,
    ROBOT_CHASSIS_ERR_CONFLICT = -13,
    ROBOT_CHASSIS_ERR_TIMEOUT = -14,
    ROBOT_CHASSIS_ERR_CHECKSUM = -15,
    ROBOT_CHASSIS_ERR_LIMIT = -16,
    ROBOT_CHASSIS_ERR_STATE = -17,
    ROBOT_CHASSIS_ERR_CANCELLED = -18
} robot_chassis_error_t;

typedef enum {
    ROBOT_CHASSIS_T_MANUAL_MOVE = 12,
    ROBOT_CHASSIS_T_GOTO_POINT = 13,
    ROBOT_CHASSIS_T_START_CHARGE = 20,
    ROBOT_CHASSIS_T_CANCEL_CHARGE = 21,
    ROBOT_CHASSIS_T_AUTO_EXPLORE = 23,
    ROBOT_CHASSIS_T_LOCK_MAP = 34,
    ROBOT_CHASSIS_T_STATUS = 42,
    ROBOT_CHASSIS_T_INIT_POSE = 44,
    ROBOT_CHASSIS_T_SOFT_STOP = 45,
    ROBOT_CHASSIS_T_START_MAPPING = 52,
    ROBOT_CHASSIS_T_CLOSE_MAPPING = 53,
    ROBOT_CHASSIS_T_SAVE_MAP = 54,
    ROBOT_CHASSIS_T_REALTIME_MAP = 55,
    ROBOT_CHASSIS_T_MAP_LIST = 58,
    ROBOT_CHASSIS_T_CLEAR_NAVIGATION = 90,
    ROBOT_CHASSIS_T_FACTORY_RESET = 109,
    ROBOT_CHASSIS_T_SET_TIME = 1002,
    ROBOT_CHASSIS_T_MAP_BACKUP_BEGIN = 1012,
    ROBOT_CHASSIS_T_UPGRADE_EXTRACT = 3003,
    ROBOT_CHASSIS_T_UPGRADE_BEGIN = 3004,
    ROBOT_CHASSIS_T_UPGRADE_CHUNK = 3005,
    ROBOT_CHASSIS_T_UPGRADE_FINISH = 3006,
    ROBOT_CHASSIS_T_MAP_BACKUP_NEXT = 3007,
    ROBOT_CHASSIS_T_WHEEL_ENABLE = 10003
} robot_chassis_t_command_t;

typedef enum {
    ROBOT_CHASSIS_CMD_HEARTBEAT = 0,
    ROBOT_CHASSIS_CMD_REBOOT
} robot_chassis_special_command_t;

typedef enum {
    ROBOT_CHASSIS_ROUTE_UNKNOWN = 0,
    ROBOT_CHASSIS_ROUTE_HEARTBEAT,
    ROBOT_CHASSIS_ROUTE_REBOOT,
    ROBOT_CHASSIS_ROUTE_STATUS,
    ROBOT_CHASSIS_ROUTE_REALTIME_MAP,
    ROBOT_CHASSIS_ROUTE_MAP_LIST,
    ROBOT_CHASSIS_ROUTE_MAP_BACKUP,
    ROBOT_CHASSIS_ROUTE_UPGRADE,
    ROBOT_CHASSIS_ROUTE_GENERIC
} robot_chassis_route_t;

typedef enum {
    ROBOT_CHASSIS_TRANSFER_NONE = 0,
    ROBOT_CHASSIS_TRANSFER_MAP_BACKUP,
    ROBOT_CHASSIS_TRANSFER_UPGRADE
} robot_chassis_transfer_kind_t;

typedef struct {
    float x;
    float y;
    float z;
} robot_chassis_pose_t;

typedef struct {
    bool tcp_connected;
    bool heartbeat_alive;
    uint8_t heartbeat_misses;
} robot_chassis_connection_state_t;

typedef struct {
    char *data;
    size_t length;
    int response_t;
    robot_chassis_special_command_t special_command;
    bool uses_special_command;
    bool dangerous;
} robot_chassis_command_t;

#ifdef __cplusplus
}
#endif

#endif

